# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: '40 01 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Git  
        run: |
          git add .
          git commit -m "Today's News Update"
          git push origin master
